### ISSUE TITLE
doc tests stopped working

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/libnotcurses-sys#14]
doc tests worked in the past, but for a while they've been failing.

I've created[ a minimal example](https://github.com/dankamongmen/libnotcurses-sys/blob/5cd981552c1e383238adb8732755eb2ea80aac03/examples/issues/examples/issue-test/src/lib.rs) to investigate the issue:

In this example, it hangs in the `running 1 test` line, until a key is pressed, then it fails continues:
```txt
$ cargo test

running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
   Doc-tests issue-test
running 1 test
test src/lib.rs - (line 13) ... FAILED
failures:
---- src/lib.rs - (line 13) stdout ----
Test executable failed (terminated by signal).
failures:
    src/lib.rs - (line 10)
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.71s
error: test failed, to rerun pass '--doc'
```

Running it with strace (via `cargo-with`, installable by running `cargo install cargo-with` ) like this:

```sh
$ cargo with "strace -s1000" -- test
```
produces the following output
[strace.txt](https://github.com/dankamongmen/libnotcurses-sys/files/7697622/strace.txt)

**Comment by joseluis** [comment]
@dankamongmen do you have any idea of what may have changed in notcurses in the last weeks that may have affected this?

**Comment by dankamongmen** [comment]
that strace output suggests everything passed...?

**Comment by joseluis** [comment]
> that strace output suggests everything passed...?

yes, with strace it passes, without strace it does not, and hangs :S
