### ISSUE TITLE
missing eff_text

### ISSUE THREAD

**Issue by Galla218** [dankamongmen/libnotcurses-sys#26]
I am trying to compile libnotcurses-sys on Ubuntu 22.04 with notcurses v3.0.9. If I compile notcurses-rs, which has libnotcurses-sys as a dependency, I get the following:
```
Compiling libnotcurses-sys v3.9.0
error[E0063]: missing field `eff_text` in initializer of `bindings::ffi::ncinput`
  --> /home/austin/.cargo/registry/src/github.com-1ecc6299db9ec823/libnotcurses-sys-3.9.0/src/input/mod.rs:66:9
   |
66 |         NcInput {
   |         ^^^^^^^ missing `eff_text`

error[E0063]: missing field `eff_text` in initializer of `bindings::ffi::ncinput`
   --> /home/austin/.cargo/registry/src/github.com-1ecc6299db9ec823/libnotcurses-sys-3.9.0/src/input/mod.rs:123:9
    |
123 |         NcInput {
    |         ^^^^^^^ missing `eff_text`
```

**Comment by joseluis** [comment]
Are you sure you are not compiling against the unpublished changes post 3.0.9 in the notcurses repository? I was waiting on the 3.0.10 release to make it compatible with the latest master branch. But the version tagged 3.0.9 4 months ago should compile.

**Comment by Galla218** [comment]
Yeah that was the issue. Thanks for the help.
