### ISSUE TITLE
Compile error on linux, ncInput missing eff_text

### ISSUE THREAD

**Issue by Kodiak-Web** [dankamongmen/libnotcurses-sys#31]
```
error[E0063]: missing field `eff_text` in initializer of `bindings::ffi::ncinput`
  --> src/input/mod.rs:66:9
   |
66 |         NcInput {
   |         ^^^^^^^ missing `eff_text`

error[E0063]: missing field `eff_text` in initializer of `bindings::ffi::ncinput`
   --> src/input/mod.rs:123:9
    |
123 |         NcInput {
    |         ^^^^^^^ missing `eff_text`

For more information about this error, try `rustc --explain E0063`.
warning: `libnotcurses-sys` (lib) generated 5 warnings
The following warnings were emitted during compilation:

warning: libnotcurses-sys@3.10.1: Keeping vendored files…

error: could not compile `libnotcurses-sys` (lib) due to 2 previous errors; 5 warnings emitted
```
added `eff_text : [0;4],` on a downloaded copy of the repo and it compiles.

**Comment by dankamongmen** [comment]
this was added to notcurses in eac79ee6801610eef7347ea8940db731480f38bd

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/commit/d8cb625b9a8c007df92dfaf2130076e18c620ab3

**Comment by dankamongmen** [comment]
@Kodiak-Web do you want to prep that as a PR? @joseluis will hopefully merge it or if he's not around, i will (once i determine that it's right, which i'm guessing it is)

**Comment by Kodiak-Web** [comment]
oh, sorry, yeah
honestly i didnt set it as a pr or anything as i didn't know if it was a my system thing or something
yeah i can make a pr rq

**Comment by joseluis** [comment]
Current version of libnotcurses-sys is compatible with the notcurses release 3.0.9. That change in the input struct hasn't been officially released yet. I was waiting for a 3.0.10 release in order to make the necessary updates... @dankamongmen Do you plan on doing a small release with the changes since december 2022?
