### ISSUE TITLE
Example won't compile on Windows 11

### ISSUE THREAD

**Issue by test3211234** [dankamongmen/libnotcurses-sys#35]
Here's the error:

```
The following warnings were emitted during compilation:

warning: libnotcurses-sys@3.11.0: Keeping vendored files…

error: failed to run custom build command for `libnotcurses-sys v3.11.0`

Caused by:
  process didn't exit successfully: `C:\Users\PC\Desktop\notcurses-rs\target\debug\build\libnotcurses-sys-0ff16d40ae52cadf\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=Keeping vendored files…
  cargo:rerun-if-env-changed=NOTCURSES_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=NOTCURSES_STATIC
  cargo:rerun-if-env-changed=NOTCURSES_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=NOTCURSES_STATIC
  cargo:rerun-if-env-changed=NOTCURSES_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at C:\Users\PC\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libnotcurses-sys-3.11.0\build/build.rs:41:14:
  pkg-config couldn't find the notcurses library: Could not run `PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags notcurses notcurses >= 3.0.11`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the libnotcurses-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by test3211234** [comment]
Tried on MacOS. Had to install nocturses and then install pkg config on top of that. Then it ran, and after the examples are finished running, my inputs are broken and it takes all inputs and puts them in the command line as some jumble. This is me trying to type after running the example:

![image](https://github.com/user-attachments/assets/e268b1aa-d756-4b58-9986-21824808590b)
(Turns out I can't even copy the text because every input I do spits out more of that jumble.)

What's going on?

**Comment by joseluis** [comment]
Hi there. I use no windows or mac, but I can try help, and maybe can run a virtual machine with windows and find a mac to test it.

I'd like to know the exact process you're following to install notcurses and the exact versions, as well as the terminal you're using in macos.

**Comment by joseluis** [comment]
I've transferend the issue to this repository, since the problem is here.

In windows this seems to be related to the [pkg-config](https://crates.io/crates/pkg-config) dependency, I see there are issues related with windows in their repo, maybe you can find there some clues https://github.com/search?q=repo%3Arust-lang%2Fpkg-config-rs+windows&type=issues

**Comment by test3211234** [comment]
Windows: I installed MSYS2 and ran the commands, as shown [here](https://github.com/dankamongmen/notcurses/blob/master/INSTALL.md#microsoft-windows). Says nothing about pkg-config.

MacOS: I used homebrew to install notcurses. For some reason, I still had to install pkg-config using `brew install pkg-config` after it errored. This is not shown in the INSTALL.md that I linked. Using Alacritty, need to test basic terminal.


Take [a look at Rust pkg-config source](https://github.com/rust-lang/pkg-config-rs/blob/91fcbdb1db2f6474a268fc022ddd1052a0f8856b/src/lib.rs#L295). They say "there's no easy fix for Windows users." That sucks, I think you should make it clear then that this library does not support Windows, or give instructions, even if difficult, on how to install pkg-config on Windows. Why do they say Notcurses supports Windows?

I tried installing pkg config using `pacman -S mingw-w64-x86_64-pkg-config` but it did nothing.

**Comment by joseluis** [comment]
The notcurses C library is a different project than the Rust bindings. The pkg-config is a requirement of the rust library, although I'd like to improve it some day.

Have you tried installed notcurses commands and do they  e.g. notcurses-info ?

I see the [CI for windows fails](https://github.com/dankamongmen/notcurses/actions/runs/11151924307/job/30996427679#step:6:124), and there seems to be some [issues related to building on windows](https://github.com/search?q=repo%3Adankamongmen%2Fnotcurses+windows&type=issues)
Maybe it works in some windows versions and not in others?

**Comment by test3211234** [comment]
> Have you tried installed notcurses commands and do they e.g. notcurses-info ?

Can you explain what this means?

**Comment by joseluis** [comment]
Once you compile notcurses there are executables fies that comes with it and you can run, like notcurses-demo and notcurses-info. If that doesn't work the rust bindings wont either

https://notcurses.com/

**Comment by test3211234** [comment]
Where do I find it and run it?

**Comment by test3211234** [comment]
Ok, I realize I didn't build it. But how do I build it? "cmake" is not recognized when I try to run the command even though I ran the MSYS2 install command. It also says sudo, which isn't on Windows. Don't know a single thing about C, sorry.

**Comment by joseluis** [comment]
You'll have to learn how to configure your environment for the requirements of the libraries you desire to use and how to compile C programs. I'm not gonna be able to assist you with all that, sorry.

**Comment by test3211234** [comment]
Crazy 😂 I thought Rust bindings were for Rust users

**Comment by test3211234** [comment]
@joseluis I built everything and ran the executables (which I can only run through MSYS2 terminal by going into the directory and doing `./executable-name` I believe, making it effectively useless), and this is what I get after (the jumble again):

![image](https://github.com/user-attachments/assets/38df727c-a050-4e3b-bc79-6b068f624adb)

It spits out jumble for every executable except ncneofetch.exe, ncplayer.exe (which just shows me a help message), nctetris (which errors and exits), and notcurses-input (input doesn't even work, can't exit). Every time I want to run something I have to close the terminal, reopen it, paste the directory in, and then run the executable from there.

But for my last question, I don't understand why you have to say that you can't help with "all that." All you had to say was use the MSYS2 terminal and use Ninja instead. It's really easy to just put that in the docs, especially for this library that non-C users can be using. But anyway, if this doesn't support Windows terminal, and input doesn't even work, I recommend you refrain from saying that this library supports Windows. It doesn't support Windows, it can just kind of barely run after doing a convoluted process. All of this has nothing to do with the original issue, pkg-config, which you still didn't even say how to install on Windows. Put it in the README.md that this doesn't support Windows.
