### ISSUE TITLE
Rust documentation fails to build in docs.rs

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/libnotcurses-sys#4]
Status: https://docs.rs/crate/libnotcurses-sys/

The [build log](https://docs.rs/crate/libnotcurses-sys/2.0.4/builds/314102) shows that it can't compile libnotcurses-sys, since it expects it to be already installed, and it isn't.

If the notcurses package were already in [Ubuntu 20.04](https://repology.org/repository/ubuntu_20_10) (the version used by the [Build environment for Rust crates](https://github.com/rust-lang/crates-build-env#adding-new-dependencies), then we could [open an issue asking to include it](https://github.com/rust-lang/crates-build-env/blob/master/.github/ISSUE_TEMPLATE/missing-linux-packages.md).

More info:
- [Add a dependency to the build environment](https://forge.rust-lang.org/docs-rs/add-dependencies.html)
- [Metadata for custom builds](https://docs.rs/about/metadata)

Until then maybe we could also modify `build.rs` to download & compile notcurses manually, like in this example: [`build.rs`](https://github.com/maidsafe/rust_sodium/blob/master/rust_sodium-sys/build.rs) & [`Cargo.toml`](https://github.com/maidsafe/rust_sodium/blob/master/rust_sodium-sys/Cargo.toml#L21)

**Comment by joseluis** [comment]
Still needs more work: [build-log](https://docs.rs/crate/libnotcurses-sys/3.0.0/builds/473371), reopening

**Comment by joseluis** [comment]
Fixed the problem of not being able to write anywhere except to OUT_DIR.

Another problem: [build-log](https://docs.rs/crate/libnotcurses-sys/3.0.1/builds/473387), it turns out there's *no internet access allowed in the builds*.

Let's see if it's possible to clone the repository by invoking a git command.

**Comment by joseluis** [comment]
ok, that's not possible either.

Next let's try to vendor the needed sourcecode files when publishing to crates.io, in an efficient way.

**Comment by joseluis** [comment]
requested the inclusion of the missing dependency `libdflalte-dev` at https://github.com/rust-lang/crates-build-env/pull/94

crossing fingers

**Comment by dankamongmen** [comment]
i imagine they'll be down, but if not, you can pass `-DUSE_DEFLATE-off` (it is undesirable, though).

**Comment by joseluis** [comment]
fixed at last!! :sweat_smile:  ! <https://docs.rs/libnotcurses-sys>

**Comment by dankamongmen** [comment]
holy shit these look fucking fantastic!

**Comment by jyn514** [comment]
@joseluis it looks like you got this working - do you still need https://github.com/rust-lang/crates-build-env/pull/94 to be merged?
